target:
- rr1_30
continuous_cols:
- coupon rate
- SP500 MD
- Average daily 1-year SP500 return
- Ratio to MA
- US Corporate Bond Yield Spread
- US Corporate Bond Yield Spread(3-5 year)
- US Corporate Bond Yield Spread(5-7 year)
- US Corporate Bond Yield Spread(7-10 year)
- US Corporate Bond Yield Spread(10+ year)
- US Generic Govt 3 Month Yield
- US Generic Govt 6 Month Yield
- US Generic Govt 12 Month Yield
- US Generic Govt 2 Year Yield
- US Generic Govt 3 Year Yield
- US Generic Govt 5 Year Yield
- US Generic Govt 7 Year Yield
- US Generic Govt 10 Year Yield
- marketcap
- sector_domicile_dtd
- sector_exchange_dtd
- sector_dtd
- PD_1_domicile_sector
- PD_3_domicile_sector
- PD_12_domicile_sector
- PD_1_domicile_subsec
- PD_3_domicile_subsec
- PD_12_domicile_subsec
- PD_1_exch_sector
- PD_3_exch_sector
- PD_12_exch_sector
- PD_1_exch_subsector
- PD_3_exch_subsector
- PD_12_exch_subsector
- PD_1_global_sector
- PD_3_global_sector
- PD_12_global_sector
- PD_1_global_subsector
- PD_3_global_subsector
- PD_12_global_subsector
- domicile_subsec_dtd
- exch_subsector_dtd
- subsector_dtd
- Stock_Index_Return
- Three_Month_Rate_After_Demean
- DTD_Level
- M_Over_B
- Sigma
- 1-year_GDP_growth
- 1-year_CPI_growth
- 1-year_PPI_growth
- 1-year_M1_growth
- 1-year_M2_growth
- employment_rate
- treasury_rate
- interest_rate
- economic_policy_uncertainty
- 1-year_housing
- mktcap_median
- ROA
- shares_out_outstanding_shares
- relative_size
- current ratio
- quick_ratio
- debt_to_equity
- liquidity_ratio
- operating_margin
- duration_in_years
- ROE
- Long-term_ratio
- MA_Index_ratio
- PD_1_sector_median
- PD_3_sector_median
- PD_12_sector_median
- dtd_sector_median
- dtd_median_exch
- PD_1_median_exch
- PD_3_median_exch
- PD_12_median_exch
- PD_1_median_domicile
- PD_3_median_domicile
- PD_12_median_domicile
- equity_market_volatility_tracker_financial_crises
- equity_market_volatility_tracker_financial_regulation
- 1_month_financial_uncertainty
- 3_month_financial_certainty
- 12_month_financial_certainty
- consumer_sentiment_index
- consumer_opinion_confidence_indicator
- last price_new
- dtd_sigma
- PD_1_pd
- PD_2_pd
- PD_3_pd
- PD_4_pd
- PD_5_pd
- PD_6_pd
- PD_7_pd
- PD_8_pd
- PD_9_pd
- PD_10_pd
- PD_11_pd
- PD_12_pd
- PD_13_pd
- PD_14_pd
- PD_15_pd
- PD_16_pd
- PD_17_pd
- PD_18_pd
- PD_19_pd
- PD_20_pd
- PD_21_pd
- PD_22_pd
- PD_23_pd
- PD_24_pd
- PD_25_pd
- PD_26_pd
- PD_27_pd
- PD_28_pd
- PD_29_pd
- PD_30_pd
- PD_31_pd
- PD_32_pd
- PD_33_pd
- PD_34_pd
- PD_35_pd
- PD_36_pd
- PD_37_pd
- PD_38_pd
- PD_39_pd
- PD_40_pd
- PD_41_pd
- PD_42_pd
- PD_43_pd
- PD_44_pd
- PD_45_pd
- PD_46_pd
- PD_47_pd
- PD_48_pd
- PD_49_pd
- PD_50_pd
- PD_51_pd
- PD_52_pd
- PD_53_pd
- PD_54_pd
- PD_55_pd
- PD_56_pd
- PD_57_pd
- PD_58_pd
- PD_59_pd
- PD_60_pd
- DTD
- NI_Over_TA
- Size
categorical_cols:
- currency
- seniorioty_adj
- domicile_country
- exchange_country
- Industry_sector
- Industry_group
- Industry_subgroup
- event_type
- event_type_subcategory_sum
- defaulted_in_last_5_years
- defaulted_in_last_6_months
date_columns: []
encode_date_columns: true
validation_split: 0.2
continuous_feature_transform: null
normalize_continuous_features: true
quantile_noise: 0
num_workers: 0
pin_memory: true
handle_unknown_categories: true
handle_missing_values: true
dataloader_kwargs: {}
task: regression
head: LinearHead
head_config:
  layers: ''
embedding_dims:
- - 14
  - 7
- - 8
  - 4
- - 24
  - 12
- - 13
  - 7
- - 12
  - 6
- - 20
  - 10
- - 48
  - 24
- - 3
  - 2
- - 16
  - 8
- - 3
  - 2
- - 3
  - 2
embedding_dropout: 0.0
batch_norm_continuous_input: true
learning_rate: 0.001
loss: MSELoss
metrics:
- mean_squared_error
metrics_prob_input:
- false
metrics_params:
- {}
target_range: null
virtual_batch_size: null
seed: 42
_module_src: models.gandalf
_model_name: GANDALFModel
_backbone_name: GANDALFBackbone
_config_name: GANDALFConfig
gflu_stages: 6
gflu_dropout: 0.0
gflu_feature_init_sparsity: 0.3
learnable_sparsity: true
batch_size: 32
data_aware_init_batch_size: 2000
fast_dev_run: false
max_epochs: 100
min_epochs: 1
max_time: null
accelerator: auto
devices: -1
devices_list: null
accumulate_grad_batches: 1
auto_lr_find: false
auto_select_gpus: true
check_val_every_n_epoch: 1
gradient_clip_val: 0.0
overfit_batches: 0.0
deterministic: false
profiler: null
early_stopping: null
early_stopping_min_delta: 0.001
early_stopping_mode: min
early_stopping_patience: 3
early_stopping_kwargs: {}
checkpoints: valid_loss
checkpoints_path: saved_models
checkpoints_every_n_epochs: 1
checkpoints_name: null
checkpoints_mode: min
checkpoints_save_top_k: 1
checkpoints_kwargs: {}
load_best: true
track_grad_norm: -1
progress_bar: none
precision: 32
trainer_kwargs: {}
optimizer: Adam
optimizer_params: {}
lr_scheduler: null
lr_scheduler_params: {}
lr_scheduler_monitor_metric: valid_loss
categorical_dim: 11
continuous_dim: 153
output_dim: 1
output_cardinality: null
categorical_cardinality:
- 14
- 8
- 24
- 13
- 12
- 20
- 48
- 3
- 16
- 3
- 3
embedded_cat_dim: 84
